name: Dispatch

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy Infra For Child 01
        id: infra
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_PARENT_CHILD_REPO }}" \
          -H "Authentication: Bearer ${{ secrets.PAT_PARENT_CHILD_REPO }}" \
          -d '{"ref":"${{ github.ref_name }}"}' \
          https://api.github.com/repos/amalay/parent/actions/workflows/test-cicd-child-01-infra.yml/dispatches

      - name: Build & Deploy App For Child 01
        if: (success() && steps.xray-scanning.conclusion != 'failure')
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_PARENT_CHILD_REPO }}" \
          -H "Authentication: Bearer ${{ secrets.PAT_PARENT_CHILD_REPO }}" \
          -d '{"ref":"${{ github.ref_name }}"}' \
          https://api.github.com/repos/amalay/parent/actions/workflows/test-cicd-child-01-app.yml/dispatches
